sudo: required
language: cpp
services:
  - docker
before_install:
  - docker pull engelphi/docker-cpp-image:latest
  - docker run -itd --name build engelphi/docker-cpp-image
  - docker exec build git clone https://github.com/engelphi/cpp-test.git /repo
script:
  - docker exec build cmake -H/repo -B/build
  - docker exec build cmake --build /build
  - docker exec build cmake --build /build --target test
